import { PrismaClient } from "@prisma/client";
import slugify from "slugify";

const prisma = new PrismaClient();

const recipes = [
  {
    title: "Weeknight Garlic Butter Pasta",
    cuisine: "Italian",
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=1200",
    ingredients: [
      "12 oz spaghetti",
      "6 tbsp butter",
      "6 cloves garlic, minced",
      "1/2 cup grated parmesan",
      "1/4 cup chopped parsley",
      "Salt and black pepper to taste",
      "Red pepper flakes (optional)",
    ],
    steps: [
      "Cook spaghetti in salted boiling water until al dente. Reserve 1 cup pasta water, then drain.",
      "Melt butter in a large skillet over medium heat. Add garlic and cook until fragrant, about 1 minute.",
      "Add drained pasta to the skillet along with a splash of pasta water. Toss to coat.",
      "Remove from heat, stir in parmesan and parsley. Add more pasta water if needed for a silky sauce.",
      "Season with salt, pepper, and red pepper flakes. Serve immediately.",
    ],
    prepTime: 5,
    cookTime: 15,
    totalTime: 20,
    servings: "4",
    popularity: 92,
  },
  {
    title: "Sheet Pan Lemon Herb Chicken",
    cuisine: "American",
    imageUrl: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=1200",
    ingredients: [
      "4 bone-in chicken thighs",
      "1 lb baby potatoes, halved",
      "2 tbsp olive oil",
      "1 lemon, sliced",
      "3 cloves garlic, minced",
      "1 tsp dried oregano",
      "1 tsp dried thyme",
      "Salt and pepper to taste",
    ],
    steps: [
      "Preheat oven to 425°F (220°C).",
      "Toss potatoes with half the olive oil, salt, and pepper on a sheet pan.",
      "Rub chicken thighs with remaining oil, garlic, oregano, thyme, salt, and pepper.",
      "Arrange chicken among the potatoes and top with lemon slices.",
      "Roast for 35-40 minutes until chicken reaches 165°F (74°C) internally and potatoes are golden.",
    ],
    prepTime: 10,
    cookTime: 40,
    totalTime: 50,
    servings: "4",
    popularity: 78,
  },
  {
    title: "Thai Basil Chicken (Pad Krapow Gai)",
    cuisine: "Thai",
    imageUrl: "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=1200",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    ingredients: [
      "1 lb ground chicken",
      "4 cloves garlic, minced",
      "3-4 Thai chilies, minced",
      "1 cup Thai basil leaves",
      "2 tbsp oyster sauce",
      "1 tbsp soy sauce",
      "1 tsp fish sauce",
      "1 tsp sugar",
      "2 tbsp vegetable oil",
      "Steamed rice and fried eggs, to serve",
    ],
    steps: [
      "Heat oil in a wok over high heat. Add garlic and chilies, stir-fry for 30 seconds.",
      "Add ground chicken and break apart, cooking until mostly browned.",
      "Stir in oyster sauce, soy sauce, fish sauce, and sugar. Cook 2-3 more minutes.",
      "Remove from heat and fold in Thai basil leaves until wilted.",
      "Serve over steamed rice topped with a fried egg.",
    ],
    prepTime: 10,
    cookTime: 10,
    totalTime: 20,
    servings: "2",
    popularity: 65,
  },
  {
    title: "Garlic Naan",
    cuisine: "Indian",
    ingredients: [
      "1 cup warm water",
      "1 tablespoon sugar",
      "2 teaspoons active dry yeast",
      "2 tablespoons plain yogurt",
      "3 tablespoons oil, plus a little more for cooking",
      "2 to 3 garlic cloves, minced",
      "3 cups all-purpose flour, plus extra for dusting",
      "1 teaspoon salt",
      "1 teaspoon baking powder",
      "2 tablespoons melted butter",
      "Chopped cilantro or parsley for finishing (optional)",
    ],
    steps: [
      "In a bowl, combine warm water, sugar, and yeast. Let it sit 5 to 10 minutes until foamy.",
      "Add yogurt, oil, minced garlic, flour, salt, and baking powder. Mix until a shaggy dough forms.",
      "Knead on a lightly floured surface for 3 to 5 minutes until smooth and elastic.",
      "Place dough in a lightly oiled bowl, cover, and let rise until doubled, about 1 hour.",
      "Divide dough into 8 to 10 pieces and roll each into an oval or teardrop shape, about 1/8-inch thick.",
      "Heat a cast iron skillet or heavy pan over medium-high heat and lightly oil it.",
      "Cook each naan for 1 to 2 minutes on the first side until bubbles form, then flip and cook 1 to 2 minutes more until golden spots appear.",
      "Brush immediately with melted butter mixed with a little minced garlic, then sprinkle with herbs if using.",
    ],
    prepTime: 75,
    cookTime: 20,
    totalTime: 95,
    servings: "8-10 naan",
    sourceUrl: "https://cafedelites.com/buttery-garlic-naan-recipe/",
    sourceName: "cafedelites.com",
    popularity: 70,
  },
  {
    title: "Garlic Pita Bread",
    cuisine: "Mediterranean",
    ingredients: [
      "2 1/4 teaspoons active dry yeast",
      "3/4 cup warm water, about 110°F",
      "1/2 teaspoon sugar",
      "2 cups all-purpose flour, plus a little more if needed",
      "1 teaspoon salt",
      "2 cloves garlic, minced",
      "1 tablespoon olive oil, plus more for the bowl and pan",
      "1/4 teaspoon dried rosemary",
      "2 teaspoons fresh thyme, chopped",
      "2 tablespoons butter, melted",
      "Extra garlic powder, parsley, or sea salt for finishing (optional)",
    ],
    steps: [
      "In a bowl, combine the warm water, sugar, and yeast. Stir and let sit for 5 to 10 minutes until foamy.",
      "Add the flour, salt, garlic, rosemary, thyme, and olive oil. Mix until a shaggy dough forms.",
      "Knead for 5 to 8 minutes until the dough is smooth and elastic. Add a little flour if it feels too sticky.",
      "Lightly oil a bowl, place the dough inside, cover it, and let it rise in a warm spot for about 1 hour, or until doubled in size.",
      "Punch down the dough and divide it into 6 equal pieces. Roll each piece into a round about 1/8 inch thick.",
      "Heat a skillet over medium-high heat and lightly oil it.",
      "Cook each pita for about 2 minutes per side, until it puffs and develops golden spots.",
      "Brush the warm pitas with melted butter mixed with a little garlic. Sprinkle with parsley or a pinch of salt if desired.",
    ],
    prepTime: 70,
    cookTime: 15,
    totalTime: 85,
    servings: "6 pitas",
    sourceUrl: "https://shepherdswife.com/2023/10/10/homemade-garlic-pita-bread/",
    sourceName: "shepherdswife.com",
    popularity: 60,
  },
  {
    title: "Garlic Pita Chips",
    cuisine: "Mediterranean",
    ingredients: [
      "4 pita breads",
      "3 tablespoons olive oil",
      "2 cloves garlic, finely minced, or 1 teaspoon garlic powder",
      "1/2 teaspoon salt",
      "Black pepper, dried parsley, paprika, or Parmesan (optional)",
    ],
    steps: [
      "Preheat the oven to 375°F.",
      "Slice each pita into halves, then cut each half into 4 wedges so you get chip-sized triangles.",
      "Mix the olive oil with the minced garlic and salt in a bowl.",
      "Brush or toss the pita wedges with the garlic oil so they're lightly coated on both sides.",
      "Arrange them in a single layer on a baking sheet.",
      "Bake for 4 to 5 minutes, flip, then bake another 3 to 5 minutes until golden and crisp.",
      "Let them cool completely; they crisp up more after coming out of the oven.",
    ],
    prepTime: 10,
    cookTime: 10,
    totalTime: 20,
    servings: "4-6",
    sourceUrl: "https://www.christinascucina.com/crunchy-garlic-baked-pita-chips/",
    sourceName: "christinascucina.com",
    popularity: 55,
  },
  {
    title: "Homemade Spaghetti Sauce",
    cuisine: "Italian",
    ingredients: [
      "1 pound ground beef",
      "Salt and black pepper, to taste",
      "1 medium onion, chopped",
      "15 ounces tomato sauce",
      "6 ounces tomato paste",
      "1/2 teaspoon Italian seasoning",
      "1 tablespoon dried parsley flakes",
      "1 teaspoon garlic powder",
      "Crushed red pepper flakes, to taste",
      "1 tablespoon Worcestershire sauce",
      "1 tablespoon granulated sugar",
      "1 cup water",
      "1/4 cup fresh basil (optional)",
      "Cooked spaghetti, for serving",
    ],
    steps: [
      "Season the ground beef with salt and pepper.",
      "In a large skillet or saucepan, brown the beef with the chopped onion over medium heat, then drain excess grease.",
      "Add the tomato sauce, tomato paste, Italian seasoning, parsley, garlic powder, red pepper flakes, Worcestershire sauce, sugar, and water.",
      "Stir well and bring the sauce to a boil.",
      "Reduce to a low simmer and cook for at least 30 minutes, or longer for deeper flavor.",
      "Stir in fresh basil near the end if using.",
      "Serve over cooked spaghetti.",
    ],
    prepTime: 10,
    cookTime: 30,
    totalTime: 40,
    servings: "4-6",
    sourceUrl: "https://tastesbetterfromscratch.com/homemade-spaghetti-sauce/",
    sourceName: "tastesbetterfromscratch.com",
    popularity: 80,
  },
  {
    title: "Italian Meatballs (No Sauce)",
    cuisine: "Italian",
    ingredients: [
      "1/2 cup fresh breadcrumbs",
      "1/4 cup milk",
      "1 large egg plus 2 egg yolks",
      "1/2 cup grated Pecorino Romano or Parmesan",
      "2 cloves garlic, minced",
      "1 teaspoon salt",
      "1/2 teaspoon black pepper",
      "1 pound ground beef",
      "1 pound ground pork",
      "1/4 cup finely chopped onion (optional)",
      "1/4 cup chopped parsley",
      "Olive oil, for browning",
    ],
    steps: [
      "Put the breadcrumbs in a small bowl and pour the milk over them. Let them soak for about 5 minutes.",
      "Add the egg, egg yolks, cheese, garlic, salt, and pepper to the breadcrumb mixture and mash into a paste.",
      "In a large bowl, combine the beef, pork, and onion if using. Add the breadcrumb mixture and parsley, then mix gently until just combined.",
      "Form into meatballs, about 2 tablespoons each for medium size or slightly larger if you want a heartier meatball.",
      "Brown them in a skillet with olive oil over medium-high heat, turning to get color on all sides.",
      "Lower the heat, cover, and cook until the meatballs reach 165°F internally.",
      "Serve plain, with a little extra cheese, or alongside pasta, bread, or roasted vegetables.",
    ],
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    servings: "6",
    sourceUrl: "https://familystylefood.com/classic-italian-meatballs-2/",
    sourceName: "familystylefood.com",
    popularity: 75,
  },
  {
    title: "Baked Eggplant Parmesan",
    cuisine: "Italian",
    ingredients: [
      "2 large eggplants, sliced into 1/4-inch rounds",
      "3 large eggs, beaten",
      "1 1/2 cups panko breadcrumbs",
      "1 1/4 cups freshly grated Parmesan, divided",
      "2 teaspoons dried oregano",
      "2 tablespoons fresh thyme leaves, or 2 teaspoons dried thyme",
      "1/2 teaspoon red pepper flakes",
      "1/2 teaspoon salt, plus more as needed",
      "Freshly ground black pepper",
      "Extra-virgin olive oil, for drizzling",
      "28 ounces marinara sauce",
      "2 large fresh mozzarella balls, thinly sliced",
      "1/3 cup fresh basil leaves",
    ],
    steps: [
      "Preheat the oven to 400°F. Line two baking sheets with parchment paper.",
      "Place the beaten eggs in a shallow dish. In a second dish, combine the panko, 1 cup Parmesan, oregano, thyme, red pepper flakes, salt, and several grinds of black pepper.",
      "Dip each eggplant slice into the egg, coating both sides. Let the excess drip off, then press it into the breadcrumb mixture. Arrange the slices in a single layer on the prepared baking sheets.",
      "Drizzle the slices lightly with olive oil. Bake for 18-25 minutes, turning once halfway through, until tender and golden brown.",
      "Spread 1/2 cup marinara over the bottom of a 9-by-13-inch baking dish. Add half of the baked eggplant, followed by 1 cup marinara and half of the mozzarella.",
      "Add the remaining eggplant, remaining marinara, and remaining mozzarella. Sprinkle the remaining 1/4 cup Parmesan over the top. Add a light drizzle of olive oil and a few pinches of salt.",
      "Bake uncovered for about 20 minutes, until the cheese is melted and bubbling.",
      "Switch the oven to broil and broil for 2-4 minutes, watching carefully, until the cheese is browned in spots.",
      "Let it rest for 5-10 minutes, then scatter fresh basil over the top and serve.",
    ],
    prepTime: 20,
    cookTime: 40,
    totalTime: 60,
    servings: "6-8",
    sourceUrl: "https://www.loveandlemons.com/eggplant-parmesan/",
    sourceName: "loveandlemons.com",
    popularity: 85,
  },
  {
    title: "Fresh Tomato Marinara",
    cuisine: "Italian",
    ingredients: [
      "5 pounds ripe Roma, plum, or vine-ripened tomatoes",
      "1/4 cup extra-virgin olive oil",
      "1 medium yellow onion, finely diced",
      "6 garlic cloves, thinly sliced or minced",
      "1 teaspoon kosher salt, plus more to taste",
      "1/2 teaspoon freshly ground black pepper",
      "1/4 teaspoon red pepper flakes (optional)",
      "1 large handful fresh basil leaves",
      "1 teaspoon dried oregano (optional)",
      "1 teaspoon sugar, only if the tomatoes taste sharply acidic",
      "1 tablespoon unsalted butter, optional, for finishing",
    ],
    steps: [
      "Bring a large pot of water to a boil. Cut a shallow \"X\" in the bottom of each tomato.",
      "Drop the tomatoes into the boiling water for 30-60 seconds, until the skins begin to split. Transfer them to a bowl of ice water.",
      "Peel off the skins, remove the cores, and roughly chop the tomatoes. Save all the juices.",
      "Heat the olive oil in a heavy-bottomed Dutch oven or wide pot over medium heat. Add the onion and cook for 5-7 minutes until soft and translucent.",
      "Add the garlic and red pepper flakes. Cook for 30-60 seconds, just until fragrant. Don't let the garlic brown.",
      "Add the tomatoes and their juices, salt, pepper, and oregano if using. Bring the sauce to a gentle simmer.",
      "Reduce the heat to low and simmer uncovered for 40-50 minutes, stirring every 10 minutes, until thick enough to coat a spoon.",
      "Add the basil during the last 10 minutes of cooking. Remove the stems before serving.",
      "Taste and adjust the salt. Add the sugar only if the tomatoes are notably acidic. Stir in the butter at the end for a rounder finish, if desired.",
    ],
    prepTime: 20,
    cookTime: 55,
    totalTime: 75,
    servings: "About 5 cups",
    sourceUrl: "https://www.oliveandmango.com/easy-fresh-tomato-marinara/",
    sourceName: "oliveandmango.com",
    popularity: 82,
  },
  {
    title: "Roasted Cauliflower Cheese",
    cuisine: "British",
    ingredients: [
      "1 large cauliflower, about 2 1/2 to 3 pounds, cut into medium florets",
      "2 tablespoons olive oil",
      "3/4 teaspoon kosher salt",
      "1/2 teaspoon black pepper",
      "3 tablespoons unsalted butter",
      "3 tablespoons all-purpose flour",
      "2 1/2 cups whole milk, warmed",
      "1/2 cup heavy cream",
      "1 teaspoon Dijon or English mustard",
      "1/4 teaspoon freshly grated nutmeg",
      "1/2 teaspoon kosher salt, plus more to taste",
      "1/4 teaspoon black pepper",
      "1 1/2 cups sharp cheddar, freshly grated",
      "3/4 cup Gruyère, freshly grated",
      "1/4 cup Parmesan, finely grated",
      "1/2 cup panko breadcrumbs",
      "1/2 cup sharp cheddar or Gruyère, grated",
      "2 tablespoons Parmesan, grated",
      "1 tablespoon melted butter",
      "1 teaspoon fresh thyme leaves, or 1/2 teaspoon dried thyme",
      "Pinch of cayenne or smoked paprika (optional)",
    ],
    steps: [
      "Heat the oven to 430°F. Toss the florets with olive oil, salt, and pepper. Spread them across a large rimmed baking sheet in one layer. Roast for 20 minutes without turning, until the edges have browned but the cauliflower remains slightly firm.",
      "Reduce the oven to 375°F. Lightly butter a 9-by-13-inch baking dish.",
      "Melt the butter in a saucepan over medium heat. Whisk in flour and cook for 2-3 minutes until a pale, smooth paste forms with no raw-flour smell; do not let it brown.",
      "Slowly whisk in about half the warm milk until smooth, then add the rest of the milk and the cream gradually. Simmer, whisking often, for 3-5 minutes until it coats the back of a spoon.",
      "Remove the pot from the heat. Whisk in mustard, nutmeg, salt, pepper, cheddar, Gruyère, and Parmesan until completely melted and smooth.",
      "Add the roasted cauliflower to the cheese sauce and fold gently to coat. Transfer everything to the baking dish.",
      "Combine panko, cheese, Parmesan, melted butter, thyme, and cayenne or paprika if using. Scatter evenly over the cauliflower.",
      "Bake at 375°F for 20-25 minutes, until bubbling around the edges and deeply golden on top. Rest 5-10 minutes before serving.",
    ],
    prepTime: 15,
    cookTime: 45,
    totalTime: 60,
    servings: "6-8",
    sourceUrl: "https://www.recipetineats.com/cauliflower-cheese/",
    sourceName: "recipetineats.com",
    popularity: 78,
  },
];

async function main() {
  for (const recipe of recipes) {
    const slug = slugify(recipe.title, { lower: true, strict: true });
    await prisma.recipe.upsert({
      where: { slug },
      update: {},
      create: {
        ...recipe,
        slug,
        ingredients: JSON.stringify(recipe.ingredients),
        steps: JSON.stringify(recipe.steps),
      },
    });
  }
  console.log(`Seeded ${recipes.length} recipes.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
